name: ci-node-workflow
on:
    pull_request:
        branches:
            - develop
jobs:
    check-application:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up node 18.7.0
              uses: actions/setup-node@v3
              with:
                  node-version: 18.7.0
            - name: Install dependencies
              run: npm install
            - name: Check application
              run:  CI=true npm test 

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}

            - name: Build and push
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                    push: true
                    tags: marcosilveira39/fc3-ci-node:latest
